### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by PaulSchweizer** [PaulSchweizer/flowpipe#23]
v0.1.0:
- [x] Api: 
  - [x] Create Nodes with arbitrary Inputs and Outputs
  - [x] Node can execute arbitrary python code
  - [x] Nodes can be connected via their inputs and outputs to form a Graph
- [x] Graphs behave like Nodes and can be used within other Graphs
- [x] Graph Evaluation in arbitray environments (Engines)
- [x] Graph is JSON serializable and deserializable
- [x] Comprehensive string representation for Graph and Nodes 
- [x] Documentation

v0.2.0:
- [ ] PySide UI
  - [ ] Deserialize Graph from json
  - [ ] Serialize Graph to json
  - [ ] Draw Connection
  - [ ] Move Node
  - [ ] Layout Graph

v0.3.0:
- [ ] PySide UI
  - [ ] Remove Node
  - [ ] Connect Node
  - [ ] Disconnect Node
  - [ ] Set Value on Node
  - [ ] Rename Node

v1.0.0:
- [ ] PySide UI
  - [ ] Evaluate Graph
    - [ ] Show dirty/clean nodes

v1.1.0:
- [ ] Celery support (Use Celery to distrbute the Graph over a network of Workers and make parallel evaluation possible)

v1.2.0:
- [x] Simplified API
  - [x] Arbitrary Node creatyed through a decorator wrapping a function that will serve as the compute method

v1.3.0:
- [ ] Framework for creating tools from a Graph
  - [ ] Parse the Graph and aggregate a simple input mask
- [ ] Verify data type on the plug, allow bool, int, float, str

**Comment by PaulSchweizer** [comment]
v0.1.0:
- [x] Api: 
  - [x] Create Nodes with arbitrary Inputs and Outputs
  - [x] Node can execute arbitrary python code
  - [x] Nodes can be connected via their inputs and outputs to form a Graph
- [x] Graphs behave like Nodes and can be used within other Graphs
- [x] Graph Evaluation in arbitray environments (Engines)
- [x] Graph is JSON serializable and deserializable
- [ ] Comprehensive string representation for Graph and Nodes 
- [ ] Documentation

v0.2.0:
- [ ] PySide UI
  - [ ] Deserialize Graph from fil json
  - [ ] Serialize Graph to json
  - [ ] Draw Connection
  - [ ] Move Node
  - [ ] Layout Graph

v0.3.0:
- [ ] PySide UI
  - [ ] Remove Node
  - [ ] Connect Node
  - [ ] Disconnect Node
  - [ ] Set Value on Node
  - [ ] Rename Node

v1.0.0:
- [ ] PySide UI
  - [ ] Evaluate Graph
    - [ ] Show dirty/clean nodes

v1.1.0:
- [ ] Celery support (Use Celery to distrbute the Graph over a network of Workers and make parallel evaluation possible)

v1.2.0:
- [ ] Simplified API
  - [ ] Arbitrary Node creatyed through a decorator wrapping a function that will serve as the compute method

v1.3.0:
- [ ] Framework for creating tools from a Graph
  - [ ] Parse the Graph and aggregate a simple input mask
- [ ] Verify data type on the plug, allow bool, int, float, str
